[package]
name = "system-program-substream"
version = "0.1.1"
edition = "2021"

[[bin]]
name = "main"
path = "src/main.rs"

[lib]
name = "system_program_substream"
crate-type = ["lib", "cdylib"]

[dependencies]
substreams = "^0.5.0"
substreams-solana = { git = "https://github.com/streamingfast/substreams-solana", branch = "master" }
substreams-database-change = "1.0.0"
substreams-solana-utils = { git = "https://github.com/0xpapercut/substreams-solana-utils", branch = "main" }
prost = "0.11"
bs58 = "0.5.0"
borsh = { version = "1.5.1", features = ["derive"] }

#substreams-solana-structured-instructions = { path = "../substreams-solana-structured-instructions" }
#substreams-solana-utils = { path = "../substreams-solana-utils" }
#spl-token-substream = { path = "../spl-token-substream" }
#substreams-solana-program-instructions = "0.1.1"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
