[workspace]
members = [
    "raydium_amm",
    "spl_token",
    "pumpfun",
    "system_program",
    "mpl_token_metadata",
]
resolver = "2"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"
